# Generated by Django 5.1.3 on 2024-11-19 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tipoavaliacao_alter_avaliacao_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoavaliacao',
            name='tipo',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='tipo_avaliacao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.tipoavaliacao'),
        ),
        migrations.AddField(
            model_name='tipoavaliacao',
            name='tipo_avaliacao',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_inicio',
            field=models.DateField(default='2000-01-01', verbose_name='data de início'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_previsao_termino',
            field=models.DateField(default='2000-01-01', verbose_name='previsão de término'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_nasc',
            field=models.DateField(default='2000-01-01', verbose_name='data de nascimento'),
        ),
    ]
