# Generated by Django 5.1.3 on 2024-11-26 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_tipoavaliacao_tipo_avaliacao_tipo_avaliacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='pessoa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.pessoa'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.curso'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='pessoa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.pessoa'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='turma',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.turma'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='area_saber',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.area'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria_total',
            field=models.IntegerField(default=0, verbose_name='carga horária'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracao_meses',
            field=models.IntegerField(default=0, verbose_name='duração'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='instituicao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.instituicao'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='area_saber',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.area'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cidade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.cidade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default=0, max_length=11),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome_da_mae',
            field=models.CharField(default='', max_length=100, verbose_name='pai'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome_do_pai',
            field=models.CharField(default='', max_length=100, verbose_name='mãe'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='ocupacao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.ocupacao'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turno',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.turno'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
    ]
