# Generated by Django 5.1.3 on 2024-11-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_pessoa_cpf_remove_pessoa_nome_da_mae_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Unidades federativas',
            },
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='UF',
        ),
    ]
