# Generated by Django 5.1.3 on 2024-11-26 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cidade_uf_alter_cidade_nome_alter_uf_sigla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='ocupacao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='turma',
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoafisica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.pessoafisica')),
                ('turma', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.turma')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
            bases=('app.pessoafisica',),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoafisica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.pessoafisica')),
                ('ocupacao', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.ocupacao')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
            bases=('app.pessoafisica',),
        ),
    ]
