# Generated by Django 5.1.3 on 2024-12-03 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_disciplina_pessoa_disciplina_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='frequencia',
            name='aluno',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.aluno'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='curso',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.curso'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='disciplina',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.disciplina'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.curso'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='instituicao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.instituicao'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='pessoa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.pessoa'),
        ),
    ]
