# Generated by Django 5.1.3 on 2024-12-03 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_matricula_pessoa_matricula_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='aluno',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.aluno'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='curso',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.curso'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='descricao',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='disciplina',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.disciplina'),
        ),
    ]
