# Generated by Django 5.1.3 on 2024-12-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_ocorrencia_pessoa_ocorrencia_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
